stages:
  - linting

linting:
  stage: linting
  image: registry.gitlab.com/mafda/python-linting
  script:
    - isort . --check-only
    - black --check .
    - flake8 .
    - find . -type f -name "*.py" | xargs pylint
  only:
    - merge_requests